### ISSUE TITLE
Enforce complete KDoc documentation

### ISSUE THREAD

**Issue by Guardiola31337** [tnorbye/kdoc-formatter#38]
This is a question / feature request? to include support for enforcing complete / well-formed KDoc documentation as part of this plugin. Is that an option that you may consider?

Tried to find that kind of check in [detekt](https://github.com/detekt/detekt) and [ktlint](https://github.com/pinterest/ktlint) but couldn't find anything.

For example, if I have the following function, I'd love to get a warning as the `@param` is not added to the KDoc.

```kotlin
/**
 * Describes awesome API.
 */
fun awesomeApi(enabled: Boolean)
```

The well-formed KDoc should be 👇 

```kotlin
/**
 * Describes awesome API.
 *
 * @param enabled set to true if you want to enable awesome API, false if not
 */
fun awesomeApi(enabled: Boolean)
```

Do you know any tools that perform this kind of enforcement? If not, is this something that could be integrated as part of the plugin?

Thanks a lot in advance and thanks for sharing this KDoc formatter plugin, it's really cool!

**Comment by tnorbye** [comment]
This feels like it should belong to the Kotlin plugin since you'd want this to be an IDE inspection, with configurable severity, an ability to suppress it, etc.

However, I should point out that this isn't actually something that the Kotlin coding conventions encourage; see 

https://kotlinlang.org/docs/coding-conventions.html#documentation-comments

"""
Generally, avoid using @param and @return tags. Instead, incorporate the description of parameters and return values directly into the documentation comment, and add links to parameters wherever they are mentioned. Use @param and @return only when a lengthy description is required which doesn't fit into the flow of the main text.

// Avoid doing this:

/**
 * Returns the absolute value of the given number.
 * @param number The number to return the absolute value for.
 * @return The absolute value.
 */
fun abs(number: Int): Int { /*...*/ }

// Do this instead:

/**
 * Returns the absolute value of the given [number].
 */
fun abs(number: Int): Int { /*...*/ }


"""

**Comment by Guardiola31337** [comment]
Thanks so much for your quick response @tnorbye 

Yeah that's exactly what I was looking at https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax 🤔 

Which is going to be even harder to confirm and enforce...

Maybe it doesn't make sense to enforce it at all 🤔 

In any case, it feels it wouldn't belong to `kdoc-formatter`. I'm going to close here.

Thanks again!
