### ISSUE TITLE
Line length miscalculation

### ISSUE THREAD

**Issue by jlkeesey** [tnorbye/kdoc-formatter#41]
Thanks for this, reformatting comments has been so irritating.

I've noticed a slight miscalculation of the line lengths used. Below is a simple file that demonstrates the issue. I set my max line length
to 90 and then reformatted one of my files (excerpted below). Notice how neither the top-level nor the method comment end at
column 90, they are in fact 90 character long + the prefix so they go over the margin (scales added for clarity). Now I can understand
meaning that max_line_length is interpreted as maximum length of comment without prefixes but that is not how the variable is
defined for anything else so it is confusing. Worse, I can't just say "ok, I need to subtract the size of the prefix" because the prefix
size is different in different locations.

```
/*
my .editorconfig:

root = true

[*.md]
max_line_length = 90
*/

// Next line starts at 3 to account for '//'
//3456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
//       1         2         3         4         5         6         7         8         9
// -------------------------- I expect breaks to occur here -----------------------------^
/**
 * The log processor. This reads each file in turn, filters for the requested items, and then
 * writes them to a file.
 */
class KDocFormatTest {
    /**
     * Process each of the files on the command line. If the name is a file we just process
     * that file. If the name is a directory, we process all .log files in that directory.
     * Otherwise, we assume that the name is a globbing spec and process each file that matches.
     * 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
     *          1         2         3         4         5         6         7         8         9
     */
    fun process() {
    }
}
```

**Comment by jlkeesey** [comment]
I forgot to say, I'm using v1.4.1.

**Comment by jlkeesey** [comment]
OK, I spent time to go through the code and I that in fact you do treat max_line_length in [*.md] as maxCommentLength which 
does not take into account the prefixes and indent which the maxLineLength does. So if the maxCommentLength is smaller
than the maxLineLength - prefixes then we just ignore the prefixes. I accept that this is what you want but I still say that it is
confusing (especially to anyone who comes after me) because on max_line_length means one things and the other
max_line_length means something else.

Where I work we want to be able to set the comment length separately from the code line length, which this does. But we also want it to be the max line length not the max comment length. Everything is there and it shouldn't be too hard to adjust the
code to take a setting for this. I looked into building/testing the plugin myself but it's a little more than I can handle right now or I would do it myself and make a PR. If I can find time to learn the plugin system I still might.

**Comment by tnorbye** [comment]
Sorry, I had somehow not noticed that these two bugs were filed in June!

Anyway, the reason markdown figures into this is that I think of this the way I think of git commit messages: they shouldn't span the whole available terminal width, they should break at 72 columns. People even write .editorconfig files for this -- 
```
[{*.md,COMMIT_EDITMSG}]
max_line_length = 72
```
It's optimized for readability. Most people set their code style line width to something much bigger -- 100, 140, ... because with nested classes and nested logic, that makes the code more readable. But that's not the case for text. Very long lines are known to be bad for readability.

I didn't want to hardcode "72" into kdoc formatter, so looking up the markdown width seems to be a good way to say "what is the codebase setting intended for readable lines?"

Did I understand your request right that what you really want is just a new custom .editorconfig setting which lets you specify the linewidth for the comment formatter, because you want the line-width behavior but a separate one from the default Kotlin one?

**Comment by jlkeesey** [comment]
I agree that the length of comments should be allowed to be different than the length of code. After rereading my comments above I realize I wasn't completely clear.

My problem is that I need the max_line_length for comments to be the maximum line length including any prefixes so that no comment exceeds the max_line_length column in the file. This is in line with how other max_line_lengths are treated. Your code will make sure that all comments are max_line_length column wide and then add the prefix so they will extend past the max_line_length column. My work has requirements that the we not exceed the column specified.

What I'm asking for is a new flag that allows me to specify that I want max_line_length to be the maximum column as well, e.g. if max_line_length is 72 and the prefix is 4 characters then the comment will not be longer than (72 - 4) = 68 characters, but on lines where the prefix is 8 characters then the comment will not be longer than (72 - 8) = 64 characters. I'm asking for a flag so that the existing behavior can stand for those who want it.

**Comment by tnorbye** [comment]
Can you clarify what you mean by a "prefix" here?

**Comment by jlkeesey** [comment]
```
12345678901234567890
/**
 * This is a comment.
 */
class foo {
   /**
    * This is a function comment.
    */
   fun bark() {}
}

```

The class comment is the text `This is a comment.` and the "prefix" is the ` * `, in this case three characters (space, star, space). The function comment is `This is a function comment.` and the "prefix" is the `    * `, in this case 6 characters (space, space, space, space, star, space).

The comment "prefix" is the part that is messing up the column count as it is not currently included in the width calculation. So the comments will extend up to prefix.length characters past the max_line_width column.

**Comment by tnorbye** [comment]
I see. Yeah, this was deliberate -- e.g. the maxCommentWidth is really only intended to ensure that the comment text itself is at most 72 (by default) characters wide, for readability. It does not take nesting into account, or comment-prefixes.

The maxLineWidth *should* handle all this correctly; the maxLineWidth is the one which is supposed to ensure that no lines are wider than X characters.

I guess I haven't quite understood what the problem is with the maxLineWidth -- is it just that you are relying on .editorconfig for formatting, and therefore you don't have a way to have a separate maxLineWidth count for comments and Kotlin code? Or is there some other subtlety here?

I could *maybe* see adjusting the maxCommentWidth to account for the the leading " *" chars, but definitely not the initial whitespace indent on each line; that would render it kinda pointless, since it's supposed to express the width of the comment itself, not the line containing the comment.

**Comment by jlkeesey** [comment]
Yeah I understand the reasoning and it's very reasonable. It's just that my work wants it both ways. ;)

The max line length may keep it from getting too long but our settings are comments: 90, code 120 so the max length won't really come into effect. I don't make the rules, I just try to deal with them.

That is why I asked if a flag could be added to change the way it works so that most people would get what it currently does but for those of us with unusual rules forced on us would also get it to work. If you don't want to do that, I understand. Let me know and I'll close this.

**Comment by tnorbye** [comment]
Well, if I understand right, the formatter's maxLineWidth is really what you want -- you just don't want it to use the one already configured for Kotlin. And kdocformatter doesn't touch the Kotlin code. 

In recent versions of the IDE plugin, you can set the max line width explicitly (overriding anything configured from editorconfig) -- see the second to last text field in https://github.com/tnorbye/kdoc-formatter/blob/main/screenshot-settings.png . And for the command line driver, in the version I'm about to update (1.5.5), explicitly passing in --max-line-width (or any other flags) will override anything found in the .editorconfig. So from the command line and in the IDE, it should let you use your own preferred max line width, independent of the .editorconfig settings for Kotlin, to force comment lines to confirm to a maximum column.

**Comment by tnorbye** [comment]
FYI 1.5.5 is released now, where specifying --max-line-width from the command line will override anything found in .editorconfig.

**Comment by jlkeesey** [comment]
I just tried the latest version and if I set the two fields to the same number I get what I want. Thanks so much.
