### ISSUE TITLE
Formatting tags should be case sensitive

### ISSUE THREAD

**Issue by davidtorosyan** [tnorbye/kdoc-formatter#59]
This is more of a suggestion, but I think `<B>` shouldn't be treated as a bold marker.

Before:
```kt
/** <A> to <B> should remain intact, not <b>bolded</b> */
fun foo() = Unit
```

After:
```kt
/** <A> to ** should remain intact, not **bolded** */
fun foo() = Unit
```

When using default options on v1.5.1.

**Comment by nreid260** [comment]
Does KDoc/Markdown use HTML tags? If so, those are case insensitive.

**Comment by davidtorosyan** [comment]
@nreid260 that's true, but I figured that it would be uncommon for kdocs to use uppercase tags in practice.

That said, over email @tnorbye pointed out that the HTML processing of kdoc engines would processes this weird, and I found that to be very true.

![image](https://user-images.githubusercontent.com/46736285/181063370-b7dc2c98-a96c-413e-9933-19a73aec1aa6.png)

You can see in this image that the (1) didn't render at all since it starts with `<`, and (2) doesn't show the `<A>` or `<B>`.

The fix then would be the escape any HTML tags that don't exist / we don't want to process, which you can see in (3).

Here's a more real-life example:

![image](https://user-images.githubusercontent.com/46736285/181063898-56e51c24-3e8e-41d6-a2b2-01b638349156.png)

I like the idea of automatically escaping these (as opposed to relying on the user), thoughts?

**Comment by nreid260** [comment]
I'm wary of adding additional tokens to user input, especially when it explicitly changes the meaning of the input text. There's a thin blurry line between helpful and infuriating.

**Comment by davidtorosyan** [comment]
> I'm wary of adding additional tokens to user input
Isn't this already doing that by replacing `<b>` with `**`?

> There's a thin blurry line between helpful and infuriating.
Agreed, but I don't know if adding backticks crosses that line. I'd call it helpful in that it improves the readability of the rendered kdocs (at least in Android Studio), and I'm not sure how it could be infuriating. I wouldn't be surprised if I'm not thinking of a case though.

**Comment by tnorbye** [comment]
I feel a little conflicted here. Changing <b>bold</b> to **bold** is a mechanical translation which should result in exactly the same rendered output (though I think ** might be mapped to <em> rather than <b>, but still, the same logical output), whereas attempting to quote code using backticks will now render the symbol as code -- and we'd have to be certain to recognize all valid HTML tags. And even recognizing valid HTML tags is tricky because of what you see in the original example -- both <A> and <B> are valid HTML tags.

It might be better for the formatter to actually emit warnings -- maybe those can be surfaced to the user from tools embedding the formatter (E.g. in kdocformatter's IDE plugin it could show these as warnings in the source code by registering an IntelliJ inspection). I agree that generics makes it common to have HTML-tag like constructs which probably don't render right. Maybe we *could* add backticks around things that *really* look like code symbols:
word bounary + PascalCase<PascalCase> + word bounary would be backticked. Won't solve all issues but probably a common class of them.

(In 1.5.4 the original request has been implemented; it no longer does case insensitive matching for converting markup.)

**Comment by nreid260** [comment]
An issue with warnings is that there's no way to acknowledge them. What should the user do if they really want the characters as typed?

**Comment by davidtorosyan** [comment]
@tnorbye 

> Changing `<b>bold</b>` to `**bold**` is a mechanical translation which should result in exactly the same rendered output

That's true for some of the transformations that kdoc-formatter does, but not all of them. The formatter also:
1. Reorders things like `@param` and `@return`
2. Removes tags like `<p>` which in the case #63 makes the list render correctly
3. Does other stuff I'm pretty sure

My point more is that if the philosophy is "fix up the kdocs so they work well", I think we can be more loose with adding/removing elements.

On the other hand, if the philosophy is "reflow but don't mess with tokens", then only whitespace should change. I think that's a valid philosophy, but not what the tool currently goes for.

@nreid260 

> An issue with warnings is that there's no way to acknowledge them

Agreed, and I don't think introducing a new warning system would be a good idea.

> What should the user do if they really want the characters as typed?

Stick them in a preformatted block with backticks? It might help to have an example where it'd really be that important but you couldn't have backticks. I understand it might be hard to come up with one, but without one it's too abstract.

**Comment by davidtorosyan** [comment]
Closing this issue since the original ask (making it case sensitive) is done.

Aggressive preformatted wrapping is really a different concern, so I can open another issue for that if it's that important (I'm not sure it is 😅).
