### ISSUE TITLE
Make plugin dynamic

### ISSUE THREAD

**Issue by rock3r** [tnorbye/kdoc-formatter#71]
The plugin requires an IDE restart every time it's updated. It would be great if it could be made properly [dynamic](https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html), so it can be loaded/unloaded/updated without having to restart the IDE.

**Comment by tnorbye** [comment]
This is fixed in 1.5.5 (uploaded to the marketplace pending JetBrains approval) - there's also a plugin zip available in the releases section here.

The reason it wasn't dynamic was surprising; it was because of this entry in the plugin.xml:

```
    <group>
    <add-to-group group-id="ProjectViewPopupMenuModifyGroup" anchor="after" relative-to-action="ReformatCode" />
      <reference ref="ReflowKDoc"/>
    </group>
```

I was surprised that an XML action registration could have that effect -- but discovered by commenting out different parts of my plugin to see where the problems were. In any case I've just commented this part out; having the Reformat action show up in the file menu isn't important now that the plugin also hooks into the IDE formatting machinery (it didn't use to).

**Comment by rock3r** [comment]
Thanks Tor! I'll pass the info along to the platform team, seems weird to me too that the action XML could cause it not to be dynamic.

**Comment by yole** [comment]
This requirement is explicitly documented:
https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html#action-group-requires-id

In this case the `<group>` is not needed at all; `<add-to-group>` can be used directly as a child of the `<reference>` element.
